-- backend/database.sql-->


CREATE TABLE Users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE
);


CREATE TABLE Lists (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES Users(id)
);


CREATE TABLE ListTranslations (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    list_id INTEGER,
    language TEXT NOT NULL,
    title TEXT NOT NULL,
    FOREIGN KEY (list_id) REFERENCES Lists(id)
);


CREATE TABLE Items (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    list_id INTEGER,
    icon TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (list_id) REFERENCES Lists(id)
);

CREATE TABLE ItemTranslations (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    item_id INTEGER,
    language TEXT NOT NULL,
    content TEXT NOT NULL,
    FOREIGN KEY (item_id) REFERENCES Items(id)
);

CREATE TABLE Meds (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);